server {
  listen 80;
  listen [::]:80;

  server_name pibt.eu www.pibt.eu;
  server_tokens off;

  location /.well-known/acme-challenge/ {
      root /var/www/certbot; 
  }

  index index.php index.html;
  root /var/www/public;

  client_max_body_size 100M; # 413 Request Entity Too Large

  location / {
    root /var/www/public;
    index  index.html index.php;
    try_files $uri $uri/ /index.php?$query_string;
  }

location ~ \.php$ {
    try_files $uri =404;
    include fastcgi.conf;
    fastcgi_pass php:9000;

    fastcgi_read_timeout 3600;
    send_timeout 3600;
}
}
