server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name humanregen.hu www.humanregen.hu 46.29.138.209;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name humanregen.hu www.humanregen.hu 46.29.138.209;
    server_tokens off;

    ssl_certificate /etc/nginx/ssl/live/humanregen.hu/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/humanregen.hu/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    index index.php index.html;
    root /var/www/public;

    client_max_body_size 100M;

    location / {
        root /var/www/public;
        index index.html index.php;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_pass php:9000;
        fastcgi_index index.php;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_read_timeout 3600;
    }
}
